### ISSUE TITLE
Idiomatic ixa

### ISSUE THREAD

**Issue by ChiragKumar9** [CDCgov/ixa-epi-isolation#28]
## Goal
Update the use of ixa in this repo to match the latest and greatest syntax on the the ixa repo's main branch.

## Context
Ixa development has been ongoing while we have been using it in this repo. As such, we may have syntax that still works but is no longer the best way to do something in our repo. We should update to use the desired ixa syntax.

## Specifications
- [ ] Use trait extensions exported from main ixa crate rather than accessing them from a module within ixa.
- [ ] Use ixa's built-in method `sample_person` to get a random person at the beginning of the simulation to infect.
- [ ] Once merged in, switch to using ixa's built-in command line runner.

**Comment by k88hudson-cfa** [comment]
Runner has landed: https://github.com/CDCgov/ixa/pull/114
